/*Creation of database plus alter of tables*/
drop database music;
create database music;
use music;

CREATE TABLE TBL_ARTIST ( 
ARTISTNO int(3), 
ARTISTNAME VARCHAR(50) NOT NULL, 
ARTISTDOB DATE, 
ARTISTGENDER CHAR(1) CHECK (ARTISTGENDER IN ('F', 'M')), CONSTRAINT ARTIST_PK PRIMARY KEY (ARTISTNO)) engine InnoDB;


CREATE TABLE TBL_SONG ( 
SONGID int(5), 
SONGNAME VARCHAR(100) NOT NULL, 
SONGDURATION int(5) CHECK (SONGDURATION >1), 
SONGGENRE CHAR(30), 
S_ARTISTNO int(3), 
CONSTRAINT SONG_PK PRIMARY KEY (SONGID), CONSTRAINT SONG_FK FOREIGN KEY 
(S_ARTISTNO) REFERENCES TBL_ARTIST (ARTISTNO)) engine InnoDB;



ALTER TABLE TBL_SONG MODIFY SONGGENRE VARCHAR(50);
ALTER TABLE TBL_ARTIST ADD HOMECOUNTRY VARCHAR(100);
ALTER TABLE TBL_ARTIST ADD RECORDINGLABEL VARCHAR(100);
ALTER TABLE TBL_ARTIST DROP COLUMN HOMECOUNTRY ;
ALTER TABLE TBL_ARTIST DROP COLUMN RECORDINGLABEL ;
ALTER TABLE TBL_SONG MODIFY SONGDURATION int(2);

use prison;
ALTER TABLE TBL_cell DROP foreign key CELL_FK;
ALTER TABLE TBL_CELL ADD CONSTRAINT CELL_FK FOREIGN KEY (C_PRISNO) REFERENCES TBL_PRISONER (PRISNO);
ALTER TABLE TBL_cell DROP primary key;
ALTER TABLE TBL_cell ADD CONSTRAINT CELL_PK PRIMARY KEY (CELLID);
COMMIT;
ALTER TABLE TBL_PRISONER DROP primary key; 
/*shouldn’t work as there is a foreign key constraint depending on this constraint, need on delete cascade.