/*Creation of a data base plus tables*/
DROP DATABASE PRISON;
Create database prison;
Use prison;
CREATE TABLE tbl_PRISONER ( 
PRISNO int(3), 
PRISNAME VARCHAR(50) , 
PRISDOB DATE, 
PRISGENDER CHAR(1) CHECK (PRISGENDER IN ('F', 'M')), 
CONSTRAINT PRIS_PK PRIMARY KEY (PRISNO)) engine innodb;

CREATE TABLE tbl_CELL ( 
CELLID int(5), 
BLOCKNAME VARCHAR(30) , 
C_PRISNO INT(3), 
CELLSIZE INT(5), 
CONSTRAINT CELL_PK PRIMARY KEY (CELLID), 
CONSTRAINT CELL_FK FOREIGN KEY (C_PRISNO) REFERENCES tbl_PRISONER (PRISNO) 
) engine innodb;